package cz.marvincz.canlii.parser

import kotlin.test.Test

class ParserTest {
    @Test
    fun parseList() {
        list.map { Parser().parse(it) }
            .forEach {
                println(it)
            }
    }
}

private val list = listOf(
    "<div id=\"cell-91699\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Summary of R v Patron\">\n                <a href=\"/en/summaries/91699\">Summary of R v Patron</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023skca34\">\n                R v Patron, 2023 SKCA 34 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/publishers/2\"><img class=\"avatar\" src=\"/publishers/2/logo\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/publishers/2\">Law Society of Saskatchewan</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91698\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Summary of R v Zheleznikov\">\n                <a href=\"/en/summaries/91698\">Summary of R v Zheleznikov</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023skca15\">\n                R v Zheleznikov, 2023 SKCA 15 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/publishers/2\"><img class=\"avatar\" src=\"/publishers/2/logo\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/publishers/2\">Law Society of Saskatchewan</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91697\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Summary of MFI Ag Services Ltd. v Kramer Ltd.\">\n                <a href=\"/en/summaries/91697\">Summary of MFI Ag Services Ltd. v Kramer Ltd.</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023skca10\">\n                MFI Ag Services Ltd. v Kramer Ltd., 2023 SKCA 10 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/publishers/2\"><img class=\"avatar\" src=\"/publishers/2/logo\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/publishers/2\">Law Society of Saskatchewan</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91696\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Summary of R v Napope\">\n                <a href=\"/en/summaries/91696\">Summary of R v Napope</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023skca1\">\n                R v Napope, 2023 SKCA 1 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/publishers/2\"><img class=\"avatar\" src=\"/publishers/2/logo\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/publishers/2\">Law Society of Saskatchewan</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91695\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Summary of R v Bileski\">\n                <a href=\"/en/summaries/91695\">Summary of R v Bileski</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2022skca150\">\n                R v Bileski, 2022 SKCA 150 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/publishers/2\"><img class=\"avatar\" src=\"/publishers/2/logo\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/publishers/2\">Law Society of Saskatchewan</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91694\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Summary of J.L. v T.T\">\n                <a href=\"/en/summaries/91694\">Summary of J.L. v T.T</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023skca43\">\n                J.L. v T.T, 2023 SKCA 43 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/publishers/2\"><img class=\"avatar\" src=\"/publishers/2/logo\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/publishers/2\">Law Society of Saskatchewan</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91693\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-opinion float-left\" title=\"Commentary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Webber Academy II: Balancing Religious Discrimination and Freedom from Religion in the Provision of Educational Services\">\n                <a href=\"/en/commentaries/91693\">Webber Academy II: Balancing Religious Discrimination and Fre...</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023abca194\">\n                Webber Academy Foundation v Alberta (Human Rights Commission), 2023 ABCA 194 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n                <span>0 Comments</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/publishers/12\"><img class=\"avatar\" src=\"/publishers/12/logo\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/search?authorOrPublisher=Howard Kislowicz and Jennifer Koshan\">Howard Kislowicz and Jennifer Koshan</a></span> &mdash; <span class=\"identifier\"><a href=\"/en/publishers/12\">ABlawg</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91692\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"Class Actions Litigation: “Territorial Competence”\">\n                <a href=\"/en/summaries/91692\">Class Actions Litigation: “Territorial Competence”</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023bcca264\">\n                Hershey Company v. Leaf, 2023 BCCA 264 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/users/56\"><img class=\"avatar\" src=\"/users/56/avatar/small\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/users/56\">Eugene Meehan, Q.C.</a></span> &mdash; <span class=\"identifier\"><a href=\"/en/publishers/4\">Supreme Advocacy LLP</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91691\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"R. v. El-Azrak (AI Case Analysis)\">\n                <a href=\"/en/summaries/91691\">R. v. El-Azrak (AI Case Analysis)</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023onca440\">\n                R. v. El-Azrak, 2023 ONCA 440 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/users/12991\"><img class=\"avatar\" src=\"/users/12991/avatar/small\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/users/12991\">CatLII</a></span> &mdash; <span class=\"identifier\"><a href=\"/en/publishers/216\">Lexum Lab</a></span><br /></div>\n                <span class=\"date\">Jul 5, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>",
    "<div id=\"cell-91687\" class=\"small grid-element cell\">\n    <hr>\n    <div class=\"clearfix\">\n            <i class=\"icon-summary float-left\" title=\"Summary\"></i>\n    </div>\n\n    <div >\n        <div class=\"headline\" title=\"England Securities Ltd. v. Ulmer (AI Case Analysis)\">\n                <a href=\"/en/summaries/91687\">England Securities Ltd. v. Ulmer (AI Case Analysis)</a>\n        </div>\n\n        <div class=\"subtitle-wrapper\">\n            <a class=\"subtitle\" href=\"/en/cases/2023bcca241\">\n                England Securities Ltd. v. Ulmer, 2023 BCCA 241 (CanLII)\n            </a>\n        </div>\n\n        <div class=\"stats\">\n            <span>0 Concurs</span>\n        </div>\n\n        <div class=\"author\">\n                    <a href=\"/en/users/12991\"><img class=\"avatar\" src=\"/users/12991/avatar/small\"></a>\n            </if>\n            <div class=\"info\">\n                <div class=\"name\">by <span class=\"identifier\"><a href=\"/en/users/12991\">CatLII</a></span> &mdash; <span class=\"identifier\"><a href=\"/en/publishers/216\">Lexum Lab</a></span><br /></div>\n                <span class=\"date\">Jul 4, 2023</span>\n            </div>\n        </div>\n    </div>\n</div>"
)